# Generated by Django 2.2.7 on 2021-01-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commemts',
            table='Comments',
        ),
        migrations.AlterModelTable(
            name='followerinfo',
            table='FollowerInfo',
        ),
        migrations.AlterModelTable(
            name='likes',
            table='Likes',
        ),
        migrations.AlterModelTable(
            name='posts',
            table='Posts',
        ),
        migrations.AlterModelTable(
            name='posttag',
            table='PostTag',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tag',
        ),
    ]
